version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: db_ordem_culto
    restart: always
    environment:
      POSTGRES_USER: user_culto
      POSTGRES_PASSWORD: culto_password
      POSTGRES_DB: db_ordem_culto
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: